language: objective-c
osx_image: xcode8

env:
  global:
  - WORKSPACE=Example/Dekoter.xcworkspace
  - SCHEME=Dekoter-Example

before_install:
- gem install xcpretty

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty